[tool.poetry]
name = "example"
description = "Example Extension"
version="0.1.0"
authors=["github_username"]
packages = [
    {include = '../'}
]

[tool.poetry.dependencies]
# You can include your python-dependencies here
python-utils = "^3.5.2"
